### PR TITLE
Redo configuration; add logging for crashid extraction

### PR DESCRIPTION
**Pull request by willkg**

### CODE REVIEW

**Comment by willkg** [comment]
Hrm. This isn't working. I need to specify a region. Plus it hoses my test harness. Boo hiss.

@milescrabill I'll look into this on Monday.

**Comment by milescrabill** [comment]
My reply didn't send. I can pass you region as an env var, say PIGEON_REGION?

**Comment by willkg** [comment]
It's more complicated because boto3 is doing a *real* call in the test harness. So either I have to mock that out (in which case I'm not actually testing it anywhere) or I have to do "if it's in tests, then just return the value, else decrypt it" kind of thing.

But yeah--we'll have to send a region, I think. Possibly more. Depends on what I need to get the boto3 code working.

**Comment by willkg** [comment]
^^^ That passes the tests. I think it'll work with decryption now.

**Comment by willkg** [comment]
Looks ok as far as I can tell. We'll know more when we run it.

**Pull request merged**
